; legacy-код использует короткие теги <?
short_open_tag = On

display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
error_reporting = E_ALL
expose_php = Off

upload_max_filesize = 35M
post_max_size = 40M

session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_samesite = Strict
session.gc_maxlifetime = 3600

date.timezone = Europe/Moscow
