-- Аудит безопасности: троттлинг перебора паролей
CREATE TABLE `NL_LOGIN_ATTEMPT`  (
  `ID_NL_LOGIN_ATTEMPT` int(11) NOT NULL AUTO_INCREMENT,
  `NL_LOGIN_ATTEMPT_IP` varchar(64) NOT NULL,
  `NL_LOGIN_ATTEMPT_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID_NL_LOGIN_ATTEMPT`) USING BTREE,
  INDEX `ip_time`(`NL_LOGIN_ATTEMPT_IP`, `NL_LOGIN_ATTEMPT_TIME`) USING BTREE
) ENGINE = InnoDB;
